// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (
    user_id, actor_user_id, action, target_type, target_id, metadata, ip, user_agent
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, actor_user_id, action, target_type, target_id, metadata, ip, user_agent, created_at
`

type InsertAuditEventParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	TargetType  *string     `json:"target_type"`
	TargetID    *string     `json:"target_id"`
	Metadata    []byte      `json:"metadata"`
	Ip          *string     `json:"ip"`
	UserAgent   *string     `json:"user_agent"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.UserID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.Ip,
		arg.UserAgent,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActorUserID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listUserAuditEvents = `-- name: ListUserAuditEvents :many
SELECT id, user_id, actor_user_id, action, target_type, target_id, metadata, ip, user_agent, created_at FROM audit_events
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListUserAuditEventsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUserAuditEvents(ctx context.Context, arg ListUserAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listUserAuditEvents, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
