// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeviceSession = `-- name: CreateDeviceSession :one
INSERT INTO device_sessions (
    user_id, jti, fingerprint, model, os_name, os_version, app_version
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, jti, fingerprint, model, os_name, os_version, app_version, last_seen_at, created_at, revoked_at
`

type CreateDeviceSessionParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Jti         pgtype.UUID `json:"jti"`
	Fingerprint *string     `json:"fingerprint"`
	Model       *string     `json:"model"`
	OsName      *string     `json:"os_name"`
	OsVersion   *string     `json:"os_version"`
	AppVersion  *string     `json:"app_version"`
}

func (q *Queries) CreateDeviceSession(ctx context.Context, arg CreateDeviceSessionParams) (DeviceSession, error) {
	row := q.db.QueryRow(ctx, createDeviceSession,
		arg.UserID,
		arg.Jti,
		arg.Fingerprint,
		arg.Model,
		arg.OsName,
		arg.OsVersion,
		arg.AppVersion,
	)
	var i DeviceSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.Fingerprint,
		&i.Model,
		&i.OsName,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveDeviceSessionByJTI = `-- name: GetActiveDeviceSessionByJTI :one
SELECT id, user_id, jti, fingerprint, model, os_name, os_version, app_version, last_seen_at, created_at, revoked_at FROM device_sessions
WHERE jti = $1 AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveDeviceSessionByJTI(ctx context.Context, jti pgtype.UUID) (DeviceSession, error) {
	row := q.db.QueryRow(ctx, getActiveDeviceSessionByJTI, jti)
	var i DeviceSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Jti,
		&i.Fingerprint,
		&i.Model,
		&i.OsName,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listUserDeviceSessions = `-- name: ListUserDeviceSessions :many
SELECT id, user_id, jti, fingerprint, model, os_name, os_version, app_version, last_seen_at, created_at, revoked_at FROM device_sessions
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserDeviceSessions(ctx context.Context, userID pgtype.UUID) ([]DeviceSession, error) {
	rows, err := q.db.Query(ctx, listUserDeviceSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceSession
	for rows.Next() {
		var i DeviceSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Jti,
			&i.Fingerprint,
			&i.Model,
			&i.OsName,
			&i.OsVersion,
			&i.AppVersion,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllOtherDeviceSessions = `-- name: RevokeAllOtherDeviceSessions :exec
UPDATE device_sessions
SET revoked_at = NOW()
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeAllOtherDeviceSessionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) RevokeAllOtherDeviceSessions(ctx context.Context, arg RevokeAllOtherDeviceSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllOtherDeviceSessions, arg.UserID, arg.ID)
	return err
}

const revokeDeviceSession = `-- name: RevokeDeviceSession :exec
UPDATE device_sessions
SET revoked_at = NOW()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeDeviceSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeDeviceSession(ctx context.Context, arg RevokeDeviceSessionParams) error {
	_, err := q.db.Exec(ctx, revokeDeviceSession, arg.ID, arg.UserID)
	return err
}

const touchDeviceSession = `-- name: TouchDeviceSession :exec
UPDATE device_sessions
SET last_seen_at = NOW()
WHERE jti = $1 AND revoked_at IS NULL AND last_seen_at < $2
`

type TouchDeviceSessionParams struct {
	Jti        pgtype.UUID        `json:"jti"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) TouchDeviceSession(ctx context.Context, arg TouchDeviceSessionParams) error {
	_, err := q.db.Exec(ctx, touchDeviceSession, arg.Jti, arg.LastSeenAt)
	return err
}
