// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (payment_id, user_id, side, amount_kobo, reference, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, payment_id, user_id, side, amount_kobo, reference, metadata, created_at
`

type InsertLedgerEntryParams struct {
	PaymentID  pgtype.UUID `json:"payment_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Side       string      `json:"side"`
	AmountKobo int64       `json:"amount_kobo"`
	Reference  string      `json:"reference"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.PaymentID,
		arg.UserID,
		arg.Side,
		arg.AmountKobo,
		arg.Reference,
		arg.Metadata,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.UserID,
		&i.Side,
		&i.AmountKobo,
		&i.Reference,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentLedger = `-- name: ListPaymentLedger :many
SELECT id, payment_id, user_id, side, amount_kobo, reference, metadata, created_at FROM ledger_entries
WHERE payment_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPaymentLedger(ctx context.Context, paymentID pgtype.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listPaymentLedger, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.UserID,
			&i.Side,
			&i.AmountKobo,
			&i.Reference,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLedger = `-- name: ListUserLedger :many
SELECT id, payment_id, user_id, side, amount_kobo, reference, metadata, created_at FROM ledger_entries
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserLedgerParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUserLedger(ctx context.Context, arg ListUserLedgerParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listUserLedger, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.UserID,
			&i.Side,
			&i.AmountKobo,
			&i.Reference,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
