// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mandates.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMandate = `-- name: CreateMandate :one
INSERT INTO mandates (user_id, authorization_code, bank_name, bank_code, last4, channel, reusable, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, authorization_code, bank_name, bank_code, last4, channel, reusable, status, is_default, created_at, revoked_at
`

type CreateMandateParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	AuthorizationCode string      `json:"authorization_code"`
	BankName          string      `json:"bank_name"`
	BankCode          *string     `json:"bank_code"`
	Last4             string      `json:"last4"`
	Channel           string      `json:"channel"`
	Reusable          bool        `json:"reusable"`
	IsDefault         bool        `json:"is_default"`
}

func (q *Queries) CreateMandate(ctx context.Context, arg CreateMandateParams) (Mandate, error) {
	row := q.db.QueryRow(ctx, createMandate,
		arg.UserID,
		arg.AuthorizationCode,
		arg.BankName,
		arg.BankCode,
		arg.Last4,
		arg.Channel,
		arg.Reusable,
		arg.IsDefault,
	)
	var i Mandate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthorizationCode,
		&i.BankName,
		&i.BankCode,
		&i.Last4,
		&i.Channel,
		&i.Reusable,
		&i.Status,
		&i.IsDefault,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDefaultMandate = `-- name: GetDefaultMandate :one
SELECT id, user_id, authorization_code, bank_name, bank_code, last4, channel, reusable, status, is_default, created_at, revoked_at FROM mandates
WHERE user_id = $1 AND status = 'active' AND is_default = TRUE
LIMIT 1
`

func (q *Queries) GetDefaultMandate(ctx context.Context, userID pgtype.UUID) (Mandate, error) {
	row := q.db.QueryRow(ctx, getDefaultMandate, userID)
	var i Mandate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthorizationCode,
		&i.BankName,
		&i.BankCode,
		&i.Last4,
		&i.Channel,
		&i.Reusable,
		&i.Status,
		&i.IsDefault,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getMandateByID = `-- name: GetMandateByID :one
SELECT id, user_id, authorization_code, bank_name, bank_code, last4, channel, reusable, status, is_default, created_at, revoked_at FROM mandates WHERE id = $1
`

func (q *Queries) GetMandateByID(ctx context.Context, id pgtype.UUID) (Mandate, error) {
	row := q.db.QueryRow(ctx, getMandateByID, id)
	var i Mandate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthorizationCode,
		&i.BankName,
		&i.BankCode,
		&i.Last4,
		&i.Channel,
		&i.Reusable,
		&i.Status,
		&i.IsDefault,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listUserMandates = `-- name: ListUserMandates :many
SELECT id, user_id, authorization_code, bank_name, bank_code, last4, channel, reusable, status, is_default, created_at, revoked_at FROM mandates
WHERE user_id = $1 AND status = 'active'
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListUserMandates(ctx context.Context, userID pgtype.UUID) ([]Mandate, error) {
	rows, err := q.db.Query(ctx, listUserMandates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mandate
	for rows.Next() {
		var i Mandate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthorizationCode,
			&i.BankName,
			&i.BankCode,
			&i.Last4,
			&i.Channel,
			&i.Reusable,
			&i.Status,
			&i.IsDefault,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMandate = `-- name: RevokeMandate :exec
UPDATE mandates
SET status = 'revoked', revoked_at = NOW(), is_default = FALSE
WHERE id = $1 AND user_id = $2
`

type RevokeMandateParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeMandate(ctx context.Context, arg RevokeMandateParams) error {
	_, err := q.db.Exec(ctx, revokeMandate, arg.ID, arg.UserID)
	return err
}

const setDefaultMandate = `-- name: SetDefaultMandate :one
UPDATE mandates
SET is_default = TRUE
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, authorization_code, bank_name, bank_code, last4, channel, reusable, status, is_default, created_at, revoked_at
`

type SetDefaultMandateParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetDefaultMandate(ctx context.Context, arg SetDefaultMandateParams) (Mandate, error) {
	row := q.db.QueryRow(ctx, setDefaultMandate, arg.ID, arg.UserID)
	var i Mandate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthorizationCode,
		&i.BankName,
		&i.BankCode,
		&i.Last4,
		&i.Channel,
		&i.Reusable,
		&i.Status,
		&i.IsDefault,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const unsetDefaultMandate = `-- name: UnsetDefaultMandate :exec
UPDATE mandates
SET is_default = FALSE
WHERE user_id = $1 AND is_default = TRUE
`

func (q *Queries) UnsetDefaultMandate(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unsetDefaultMandate, userID)
	return err
}
