// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceSession struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Jti         pgtype.UUID        `json:"jti"`
	Fingerprint *string            `json:"fingerprint"`
	Model       *string            `json:"model"`
	OsName      *string            `json:"os_name"`
	OsVersion   *string            `json:"os_version"`
	AppVersion  *string            `json:"app_version"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type LedgerEntry struct {
	ID         int64              `json:"id"`
	PaymentID  pgtype.UUID        `json:"payment_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Side       string             `json:"side"`
	AmountKobo int64              `json:"amount_kobo"`
	Reference  string             `json:"reference"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Mandate struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	AuthorizationCode string             `json:"authorization_code"`
	BankName          string             `json:"bank_name"`
	BankCode          *string            `json:"bank_code"`
	Last4             string             `json:"last4"`
	Channel           string             `json:"channel"`
	Reusable          bool               `json:"reusable"`
	Status            string             `json:"status"`
	IsDefault         bool               `json:"is_default"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

type OtpRequest struct {
	ID          pgtype.UUID        `json:"id"`
	Phone       string             `json:"phone"`
	CodeHash    string             `json:"code_hash"`
	Purpose     string             `json:"purpose"`
	Attempts    int16              `json:"attempts"`
	MaxAttempts int16              `json:"max_attempts"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                  pgtype.UUID        `json:"id"`
	TokenID             pgtype.UUID        `json:"token_id"`
	SenderUserID        pgtype.UUID        `json:"sender_user_id"`
	ReceiverUserID      pgtype.UUID        `json:"receiver_user_id"`
	SenderMandateID     pgtype.UUID        `json:"sender_mandate_id"`
	AmountKobo          int64              `json:"amount_kobo"`
	IdempotencyKey      string             `json:"idempotency_key"`
	ChargeReference     *string            `json:"charge_reference"`
	ChargeStatus        *string            `json:"charge_status"`
	TransferReference   *string            `json:"transfer_reference"`
	TransferStatus      *string            `json:"transfer_status"`
	Status              string             `json:"status"`
	FailureReason       *string            `json:"failure_reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	SettledAt           pgtype.Timestamptz `json:"settled_at"`
	RefundsPaymentID    pgtype.UUID        `json:"refunds_payment_id"`
	AutoRefundReference *string            `json:"auto_refund_reference"`
}

type PendingLimitChange struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	PerTxLimitKobo  int64              `json:"per_tx_limit_kobo"`
	PerDayLimitKobo int64              `json:"per_day_limit_kobo"`
	AppliesAt       pgtype.Timestamptz `json:"applies_at"`
	AppliedAt       pgtype.Timestamptz `json:"applied_at"`
	CancelledAt     pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Token struct {
	ID               pgtype.UUID        `json:"id"`
	Code             string             `json:"code"`
	IssuedByUserID   pgtype.UUID        `json:"issued_by_user_id"`
	AmountKobo       int64              `json:"amount_kobo"`
	Note             *string            `json:"note"`
	Status           string             `json:"status"`
	ClaimedByUserID  pgtype.UUID        `json:"claimed_by_user_id"`
	ClaimedAt        pgtype.Timestamptz `json:"claimed_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	SettledPaymentID pgtype.UUID        `json:"settled_payment_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TrustedMerchant struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	MerchantUserID pgtype.UUID        `json:"merchant_user_id"`
	PerTxCapKobo   int64              `json:"per_tx_cap_kobo"`
	Label          *string            `json:"label"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Phone           string             `json:"phone"`
	FullName        *string            `json:"full_name"`
	BvnHash         *string            `json:"bvn_hash"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	KycTier         int16              `json:"kyc_tier"`
	KycStatus       string             `json:"kyc_status"`
	Nuban           *string            `json:"nuban"`
	BankCode        *string            `json:"bank_code"`
	AccountName     *string            `json:"account_name"`
	PerTxLimitKobo  int64              `json:"per_tx_limit_kobo"`
	PerDayLimitKobo int64              `json:"per_day_limit_kobo"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
