// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTPRequest = `-- name: CreateOTPRequest :one
INSERT INTO otp_requests (phone, code_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, phone, code_hash, purpose, attempts, max_attempts, expires_at, verified_at, created_at
`

type CreateOTPRequestParams struct {
	Phone     string             `json:"phone"`
	CodeHash  string             `json:"code_hash"`
	Purpose   string             `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOTPRequest(ctx context.Context, arg CreateOTPRequestParams) (OtpRequest, error) {
	row := q.db.QueryRow(ctx, createOTPRequest,
		arg.Phone,
		arg.CodeHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i OtpRequest
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const expirePreviousOTPs = `-- name: ExpirePreviousOTPs :exec
UPDATE otp_requests
SET expires_at = NOW() - INTERVAL '1 second'
WHERE phone = $1 AND purpose = $2 AND verified_at IS NULL AND expires_at > NOW()
`

type ExpirePreviousOTPsParams struct {
	Phone   string `json:"phone"`
	Purpose string `json:"purpose"`
}

func (q *Queries) ExpirePreviousOTPs(ctx context.Context, arg ExpirePreviousOTPsParams) error {
	_, err := q.db.Exec(ctx, expirePreviousOTPs, arg.Phone, arg.Purpose)
	return err
}

const getLatestOTPRequest = `-- name: GetLatestOTPRequest :one
SELECT id, phone, code_hash, purpose, attempts, max_attempts, expires_at, verified_at, created_at FROM otp_requests
WHERE phone = $1 AND purpose = $2 AND verified_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestOTPRequestParams struct {
	Phone   string `json:"phone"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetLatestOTPRequest(ctx context.Context, arg GetLatestOTPRequestParams) (OtpRequest, error) {
	row := q.db.QueryRow(ctx, getLatestOTPRequest, arg.Phone, arg.Purpose)
	var i OtpRequest
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :one
UPDATE otp_requests
SET attempts = attempts + 1
WHERE id = $1
RETURNING id, phone, code_hash, purpose, attempts, max_attempts, expires_at, verified_at, created_at
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) (OtpRequest, error) {
	row := q.db.QueryRow(ctx, incrementOTPAttempts, id)
	var i OtpRequest
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOTPVerified = `-- name: MarkOTPVerified :exec
UPDATE otp_requests
SET verified_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOTPVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOTPVerified, id)
	return err
}
