// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    token_id, sender_user_id, receiver_user_id, sender_mandate_id,
    amount_kobo, idempotency_key, refunds_payment_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id
`

type CreatePaymentParams struct {
	TokenID          pgtype.UUID `json:"token_id"`
	SenderUserID     pgtype.UUID `json:"sender_user_id"`
	ReceiverUserID   pgtype.UUID `json:"receiver_user_id"`
	SenderMandateID  pgtype.UUID `json:"sender_mandate_id"`
	AmountKobo       int64       `json:"amount_kobo"`
	IdempotencyKey   string      `json:"idempotency_key"`
	RefundsPaymentID pgtype.UUID `json:"refunds_payment_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.TokenID,
		arg.SenderUserID,
		arg.ReceiverUserID,
		arg.SenderMandateID,
		arg.AmountKobo,
		arg.IdempotencyKey,
		arg.RefundsPaymentID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
	)
	return i, err
}

const getPaymentByChargeReference = `-- name: GetPaymentByChargeReference :one
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id FROM payments WHERE charge_reference = $1
`

func (q *Queries) GetPaymentByChargeReference(ctx context.Context, chargeReference *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByChargeReference, chargeReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id FROM payments WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
	)
	return i, err
}

const getPaymentByTransferReference = `-- name: GetPaymentByTransferReference :one
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id FROM payments WHERE transfer_reference = $1
`

func (q *Queries) GetPaymentByTransferReference(ctx context.Context, transferReference *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByTransferReference, transferReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
	)
	return i, err
}

const listStuckPayments = `-- name: ListStuckPayments :many
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id FROM payments
WHERE status IN ('debiting','transferring','settling','initiated')
  AND updated_at < $1
ORDER BY updated_at ASC
LIMIT $2
`

type ListStuckPaymentsParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListStuckPayments(ctx context.Context, arg ListStuckPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listStuckPayments, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.SenderUserID,
			&i.ReceiverUserID,
			&i.SenderMandateID,
			&i.AmountKobo,
			&i.IdempotencyKey,
			&i.ChargeReference,
			&i.ChargeStatus,
			&i.TransferReference,
			&i.TransferStatus,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettledAt,
			&i.RefundsPaymentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPayments = `-- name: ListUserPayments :many
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id FROM payments
WHERE sender_user_id = $1 OR receiver_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserPaymentsParams struct {
	SenderUserID pgtype.UUID `json:"sender_user_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

func (q *Queries) ListUserPayments(ctx context.Context, arg ListUserPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listUserPayments, arg.SenderUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.SenderUserID,
			&i.ReceiverUserID,
			&i.SenderMandateID,
			&i.AmountKobo,
			&i.IdempotencyKey,
			&i.ChargeReference,
			&i.ChargeStatus,
			&i.TransferReference,
			&i.TransferStatus,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettledAt,
			&i.RefundsPaymentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payments
SET status = 'failed',
    failure_reason = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id
`

type MarkPaymentFailedParams struct {
	ID            pgtype.UUID `json:"id"`
	FailureReason *string     `json:"failure_reason"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, arg.ID, arg.FailureReason)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
	)
	return i, err
}

const markPaymentSettled = `-- name: MarkPaymentSettled :one
UPDATE payments
SET status = 'settled',
    settled_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id
`

func (q *Queries) MarkPaymentSettled(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentSettled, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
	)
	return i, err
}

const updatePaymentCharge = `-- name: UpdatePaymentCharge :one
UPDATE payments
SET charge_reference = $2,
    charge_status = $3,
    status = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id
`

type UpdatePaymentChargeParams struct {
	ID              pgtype.UUID `json:"id"`
	ChargeReference *string     `json:"charge_reference"`
	ChargeStatus    *string     `json:"charge_status"`
	Status          string      `json:"status"`
}

func (q *Queries) UpdatePaymentCharge(ctx context.Context, arg UpdatePaymentChargeParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentCharge,
		arg.ID,
		arg.ChargeReference,
		arg.ChargeStatus,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
	)
	return i, err
}

const updatePaymentTransfer = `-- name: UpdatePaymentTransfer :one
UPDATE payments
SET transfer_reference = $2,
    transfer_status = $3,
    status = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id
`

type UpdatePaymentTransferParams struct {
	ID                pgtype.UUID `json:"id"`
	TransferReference *string     `json:"transfer_reference"`
	TransferStatus    *string     `json:"transfer_status"`
	Status            string      `json:"status"`
}

func (q *Queries) UpdatePaymentTransfer(ctx context.Context, arg UpdatePaymentTransferParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentTransfer,
		arg.ID,
		arg.TransferReference,
		arg.TransferStatus,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
	)
	return i, err
}
