// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    token_id, sender_user_id, receiver_user_id, sender_mandate_id,
    amount_kobo, idempotency_key, refunds_payment_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at
`

type CreatePaymentParams struct {
	TokenID          pgtype.UUID `json:"token_id"`
	SenderUserID     pgtype.UUID `json:"sender_user_id"`
	ReceiverUserID   pgtype.UUID `json:"receiver_user_id"`
	SenderMandateID  pgtype.UUID `json:"sender_mandate_id"`
	AmountKobo       int64       `json:"amount_kobo"`
	IdempotencyKey   string      `json:"idempotency_key"`
	RefundsPaymentID pgtype.UUID `json:"refunds_payment_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.TokenID,
		arg.SenderUserID,
		arg.ReceiverUserID,
		arg.SenderMandateID,
		arg.AmountKobo,
		arg.IdempotencyKey,
		arg.RefundsPaymentID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const getPaymentByChargeReference = `-- name: GetPaymentByChargeReference :one
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at FROM payments WHERE charge_reference = $1
`

func (q *Queries) GetPaymentByChargeReference(ctx context.Context, chargeReference *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByChargeReference, chargeReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at FROM payments WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const getPaymentByTransferReference = `-- name: GetPaymentByTransferReference :one
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at FROM payments WHERE transfer_reference = $1
`

func (q *Queries) GetPaymentByTransferReference(ctx context.Context, transferReference *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByTransferReference, transferReference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const holdPayment = `-- name: HoldPayment :one
UPDATE payments
SET status = 'held',
    hold_expires_at = $2,
    updated_at = NOW()
WHERE id = $1 AND status = 'transferring'
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at
`

type HoldPaymentParams struct {
	ID            pgtype.UUID        `json:"id"`
	HoldExpiresAt pgtype.Timestamptz `json:"hold_expires_at"`
}

// Conditional on status=transferring so the held path never trips a payment
// that's already moved through the normal flow.
func (q *Queries) HoldPayment(ctx context.Context, arg HoldPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, holdPayment, arg.ID, arg.HoldExpiresAt)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const listExpiredHolds = `-- name: ListExpiredHolds :many
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at FROM payments
WHERE status = 'held'
  AND hold_expires_at IS NOT NULL
  AND hold_expires_at <= $1
ORDER BY hold_expires_at ASC
LIMIT $2
`

type ListExpiredHoldsParams struct {
	HoldExpiresAt pgtype.Timestamptz `json:"hold_expires_at"`
	Limit         int32              `json:"limit"`
}

// For the reconciler safety net — picks up holds where the in-process
// timer was lost across a restart.
func (q *Queries) ListExpiredHolds(ctx context.Context, arg ListExpiredHoldsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listExpiredHolds, arg.HoldExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.SenderUserID,
			&i.ReceiverUserID,
			&i.SenderMandateID,
			&i.AmountKobo,
			&i.IdempotencyKey,
			&i.ChargeReference,
			&i.ChargeStatus,
			&i.TransferReference,
			&i.TransferStatus,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettledAt,
			&i.RefundsPaymentID,
			&i.AutoRefundReference,
			&i.HoldExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForAutoRefund = `-- name: ListPaymentsForAutoRefund :many
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at FROM payments
WHERE status IN ('debiting','transferring','settling')
  AND charge_status = 'success'
  AND auto_refund_reference IS NULL
  AND created_at < $1
ORDER BY created_at ASC
LIMIT $2
`

type ListPaymentsForAutoRefundParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListPaymentsForAutoRefund(ctx context.Context, arg ListPaymentsForAutoRefundParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsForAutoRefund, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.SenderUserID,
			&i.ReceiverUserID,
			&i.SenderMandateID,
			&i.AmountKobo,
			&i.IdempotencyKey,
			&i.ChargeReference,
			&i.ChargeStatus,
			&i.TransferReference,
			&i.TransferStatus,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettledAt,
			&i.RefundsPaymentID,
			&i.AutoRefundReference,
			&i.HoldExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckPayments = `-- name: ListStuckPayments :many
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at FROM payments
WHERE status IN ('debiting','transferring','settling','initiated')
  AND updated_at < $1
ORDER BY updated_at ASC
LIMIT $2
`

type ListStuckPaymentsParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListStuckPayments(ctx context.Context, arg ListStuckPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listStuckPayments, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.SenderUserID,
			&i.ReceiverUserID,
			&i.SenderMandateID,
			&i.AmountKobo,
			&i.IdempotencyKey,
			&i.ChargeReference,
			&i.ChargeStatus,
			&i.TransferReference,
			&i.TransferStatus,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettledAt,
			&i.RefundsPaymentID,
			&i.AutoRefundReference,
			&i.HoldExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPayments = `-- name: ListUserPayments :many
SELECT id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at FROM payments
WHERE sender_user_id = $1 OR receiver_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserPaymentsParams struct {
	SenderUserID pgtype.UUID `json:"sender_user_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

func (q *Queries) ListUserPayments(ctx context.Context, arg ListUserPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listUserPayments, arg.SenderUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.SenderUserID,
			&i.ReceiverUserID,
			&i.SenderMandateID,
			&i.AmountKobo,
			&i.IdempotencyKey,
			&i.ChargeReference,
			&i.ChargeStatus,
			&i.TransferReference,
			&i.TransferStatus,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SettledAt,
			&i.RefundsPaymentID,
			&i.AutoRefundReference,
			&i.HoldExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentAutoRefunded = `-- name: MarkPaymentAutoRefunded :one
UPDATE payments
SET auto_refund_reference = $2,
    status = 'failed',
    failure_reason = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at
`

type MarkPaymentAutoRefundedParams struct {
	ID                  pgtype.UUID `json:"id"`
	AutoRefundReference *string     `json:"auto_refund_reference"`
	FailureReason       *string     `json:"failure_reason"`
}

func (q *Queries) MarkPaymentAutoRefunded(ctx context.Context, arg MarkPaymentAutoRefundedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentAutoRefunded, arg.ID, arg.AutoRefundReference, arg.FailureReason)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE payments
SET status = 'failed',
    failure_reason = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at
`

type MarkPaymentFailedParams struct {
	ID            pgtype.UUID `json:"id"`
	FailureReason *string     `json:"failure_reason"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, arg.ID, arg.FailureReason)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const markPaymentRefunded = `-- name: MarkPaymentRefunded :one
UPDATE payments
SET status = 'refunded',
    auto_refund_reference = $2,
    failure_reason = $3,
    updated_at = NOW()
WHERE id = $1 AND status = 'held'
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at
`

type MarkPaymentRefundedParams struct {
	ID                  pgtype.UUID `json:"id"`
	AutoRefundReference *string     `json:"auto_refund_reference"`
	FailureReason       *string     `json:"failure_reason"`
}

// Conditional on status=held so undo can't fire after the hold has been
// released into transfer.
func (q *Queries) MarkPaymentRefunded(ctx context.Context, arg MarkPaymentRefundedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentRefunded, arg.ID, arg.AutoRefundReference, arg.FailureReason)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const markPaymentSettled = `-- name: MarkPaymentSettled :one
UPDATE payments
SET status = 'settled',
    settled_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at
`

func (q *Queries) MarkPaymentSettled(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentSettled, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const releaseHeldPayment = `-- name: ReleaseHeldPayment :one
UPDATE payments
SET status = 'transferring',
    updated_at = NOW()
WHERE id = $1 AND status = 'held'
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at
`

// Conditional on status=held so the undo path and the release path don't
// both try to advance the payment. Whoever wins the UPDATE proceeds.
func (q *Queries) ReleaseHeldPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, releaseHeldPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const updatePaymentCharge = `-- name: UpdatePaymentCharge :one
UPDATE payments
SET charge_reference = $2,
    charge_status = $3,
    status = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at
`

type UpdatePaymentChargeParams struct {
	ID              pgtype.UUID `json:"id"`
	ChargeReference *string     `json:"charge_reference"`
	ChargeStatus    *string     `json:"charge_status"`
	Status          string      `json:"status"`
}

func (q *Queries) UpdatePaymentCharge(ctx context.Context, arg UpdatePaymentChargeParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentCharge,
		arg.ID,
		arg.ChargeReference,
		arg.ChargeStatus,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}

const updatePaymentTransfer = `-- name: UpdatePaymentTransfer :one
UPDATE payments
SET transfer_reference = $2,
    transfer_status = $3,
    status = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, token_id, sender_user_id, receiver_user_id, sender_mandate_id, amount_kobo, idempotency_key, charge_reference, charge_status, transfer_reference, transfer_status, status, failure_reason, created_at, updated_at, settled_at, refunds_payment_id, auto_refund_reference, hold_expires_at
`

type UpdatePaymentTransferParams struct {
	ID                pgtype.UUID `json:"id"`
	TransferReference *string     `json:"transfer_reference"`
	TransferStatus    *string     `json:"transfer_status"`
	Status            string      `json:"status"`
}

func (q *Queries) UpdatePaymentTransfer(ctx context.Context, arg UpdatePaymentTransferParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentTransfer,
		arg.ID,
		arg.TransferReference,
		arg.TransferStatus,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.SenderUserID,
		&i.ReceiverUserID,
		&i.SenderMandateID,
		&i.AmountKobo,
		&i.IdempotencyKey,
		&i.ChargeReference,
		&i.ChargeStatus,
		&i.TransferReference,
		&i.TransferStatus,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SettledAt,
		&i.RefundsPaymentID,
		&i.AutoRefundReference,
		&i.HoldExpiresAt,
	)
	return i, err
}
