// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_limits.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingLimitChanges = `-- name: CancelPendingLimitChanges :exec
UPDATE pending_limit_changes
SET cancelled_at = NOW()
WHERE user_id = $1 AND applied_at IS NULL AND cancelled_at IS NULL
`

func (q *Queries) CancelPendingLimitChanges(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelPendingLimitChanges, userID)
	return err
}

const createPendingLimitChange = `-- name: CreatePendingLimitChange :one
INSERT INTO pending_limit_changes (user_id, per_tx_limit_kobo, per_day_limit_kobo, applies_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, per_tx_limit_kobo, per_day_limit_kobo, applies_at, applied_at, cancelled_at, created_at
`

type CreatePendingLimitChangeParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	PerTxLimitKobo  int64              `json:"per_tx_limit_kobo"`
	PerDayLimitKobo int64              `json:"per_day_limit_kobo"`
	AppliesAt       pgtype.Timestamptz `json:"applies_at"`
}

func (q *Queries) CreatePendingLimitChange(ctx context.Context, arg CreatePendingLimitChangeParams) (PendingLimitChange, error) {
	row := q.db.QueryRow(ctx, createPendingLimitChange,
		arg.UserID,
		arg.PerTxLimitKobo,
		arg.PerDayLimitKobo,
		arg.AppliesAt,
	)
	var i PendingLimitChange
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PerTxLimitKobo,
		&i.PerDayLimitKobo,
		&i.AppliesAt,
		&i.AppliedAt,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingLimitChange = `-- name: GetPendingLimitChange :one
SELECT id, user_id, per_tx_limit_kobo, per_day_limit_kobo, applies_at, applied_at, cancelled_at, created_at FROM pending_limit_changes
WHERE user_id = $1 AND applied_at IS NULL AND cancelled_at IS NULL
LIMIT 1
`

func (q *Queries) GetPendingLimitChange(ctx context.Context, userID pgtype.UUID) (PendingLimitChange, error) {
	row := q.db.QueryRow(ctx, getPendingLimitChange, userID)
	var i PendingLimitChange
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PerTxLimitKobo,
		&i.PerDayLimitKobo,
		&i.AppliesAt,
		&i.AppliedAt,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDuePendingLimits = `-- name: ListDuePendingLimits :many
SELECT id, user_id, per_tx_limit_kobo, per_day_limit_kobo, applies_at, applied_at, cancelled_at, created_at FROM pending_limit_changes
WHERE applied_at IS NULL AND cancelled_at IS NULL AND applies_at <= $1
ORDER BY applies_at ASC
LIMIT $2
`

type ListDuePendingLimitsParams struct {
	AppliesAt pgtype.Timestamptz `json:"applies_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListDuePendingLimits(ctx context.Context, arg ListDuePendingLimitsParams) ([]PendingLimitChange, error) {
	rows, err := q.db.Query(ctx, listDuePendingLimits, arg.AppliesAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingLimitChange
	for rows.Next() {
		var i PendingLimitChange
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PerTxLimitKobo,
			&i.PerDayLimitKobo,
			&i.AppliesAt,
			&i.AppliedAt,
			&i.CancelledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPendingLimitApplied = `-- name: MarkPendingLimitApplied :exec
UPDATE pending_limit_changes
SET applied_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPendingLimitApplied(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPendingLimitApplied, id)
	return err
}
