// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUserPushTokens = `-- name: ListUserPushTokens :many
SELECT id, user_id, device_session_id, fcm_token, platform, last_seen_at, created_at, revoked_at FROM push_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserPushTokens(ctx context.Context, userID pgtype.UUID) ([]PushToken, error) {
	rows, err := q.db.Query(ctx, listUserPushTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushToken
	for rows.Next() {
		var i PushToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceSessionID,
			&i.FcmToken,
			&i.Platform,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPushTokensExceptSession = `-- name: ListUserPushTokensExceptSession :many
SELECT id, user_id, device_session_id, fcm_token, platform, last_seen_at, created_at, revoked_at FROM push_tokens
WHERE user_id = $1 AND revoked_at IS NULL
  AND (device_session_id IS NULL OR device_session_id <> $2)
ORDER BY last_seen_at DESC
`

type ListUserPushTokensExceptSessionParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	DeviceSessionID pgtype.UUID `json:"device_session_id"`
}

func (q *Queries) ListUserPushTokensExceptSession(ctx context.Context, arg ListUserPushTokensExceptSessionParams) ([]PushToken, error) {
	rows, err := q.db.Query(ctx, listUserPushTokensExceptSession, arg.UserID, arg.DeviceSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushToken
	for rows.Next() {
		var i PushToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceSessionID,
			&i.FcmToken,
			&i.Platform,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePushToken = `-- name: RevokePushToken :exec
UPDATE push_tokens
SET revoked_at = NOW()
WHERE fcm_token = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokePushToken(ctx context.Context, fcmToken string) error {
	_, err := q.db.Exec(ctx, revokePushToken, fcmToken)
	return err
}

const revokePushTokensForSession = `-- name: RevokePushTokensForSession :exec
UPDATE push_tokens
SET revoked_at = NOW()
WHERE device_session_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokePushTokensForSession(ctx context.Context, deviceSessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokePushTokensForSession, deviceSessionID)
	return err
}

const upsertPushToken = `-- name: UpsertPushToken :one
INSERT INTO push_tokens (user_id, device_session_id, fcm_token, platform)
VALUES ($1, $2, $3, $4)
ON CONFLICT (fcm_token) WHERE revoked_at IS NULL
DO UPDATE SET user_id = EXCLUDED.user_id,
              device_session_id = EXCLUDED.device_session_id,
              platform = EXCLUDED.platform,
              last_seen_at = NOW()
RETURNING id, user_id, device_session_id, fcm_token, platform, last_seen_at, created_at, revoked_at
`

type UpsertPushTokenParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	DeviceSessionID pgtype.UUID `json:"device_session_id"`
	FcmToken        string      `json:"fcm_token"`
	Platform        string      `json:"platform"`
}

func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) (PushToken, error) {
	row := q.db.QueryRow(ctx, upsertPushToken,
		arg.UserID,
		arg.DeviceSessionID,
		arg.FcmToken,
		arg.Platform,
	)
	var i PushToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceSessionID,
		&i.FcmToken,
		&i.Platform,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
