// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelPendingLimitChanges(ctx context.Context, userID pgtype.UUID) error
	ClaimToken(ctx context.Context, arg ClaimTokenParams) (Token, error)
	CreateDeviceSession(ctx context.Context, arg CreateDeviceSessionParams) (DeviceSession, error)
	CreateMandate(ctx context.Context, arg CreateMandateParams) (Mandate, error)
	CreateOTPRequest(ctx context.Context, arg CreateOTPRequestParams) (OtpRequest, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePendingLimitChange(ctx context.Context, arg CreatePendingLimitChangeParams) (PendingLimitChange, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateUser(ctx context.Context, phone string) (User, error)
	DeleteTrustedMerchant(ctx context.Context, arg DeleteTrustedMerchantParams) error
	ExpirePreviousOTPs(ctx context.Context, arg ExpirePreviousOTPsParams) error
	ExpireStaleTokens(ctx context.Context) error
	GetActiveDeviceSessionByJTI(ctx context.Context, jti pgtype.UUID) (DeviceSession, error)
	GetDefaultMandate(ctx context.Context, userID pgtype.UUID) (Mandate, error)
	GetLatestOTPRequest(ctx context.Context, arg GetLatestOTPRequestParams) (OtpRequest, error)
	GetMandateByID(ctx context.Context, id pgtype.UUID) (Mandate, error)
	GetPaymentByChargeReference(ctx context.Context, chargeReference *string) (Payment, error)
	GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error)
	GetPaymentByTransferReference(ctx context.Context, transferReference *string) (Payment, error)
	GetPendingLimitChange(ctx context.Context, userID pgtype.UUID) (PendingLimitChange, error)
	GetTokenByCode(ctx context.Context, code string) (Token, error)
	GetTokenByID(ctx context.Context, id pgtype.UUID) (Token, error)
	GetTrustedMerchantCap(ctx context.Context, arg GetTrustedMerchantCapParams) (int64, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	// Conditional on status=transferring so the held path never trips a payment
	// that's already moved through the normal flow.
	HoldPayment(ctx context.Context, arg HoldPaymentParams) (Payment, error)
	IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) (OtpRequest, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	ListDuePendingLimits(ctx context.Context, arg ListDuePendingLimitsParams) ([]PendingLimitChange, error)
	// For the reconciler safety net — picks up holds where the in-process
	// timer was lost across a restart.
	ListExpiredHolds(ctx context.Context, arg ListExpiredHoldsParams) ([]Payment, error)
	ListPaymentLedger(ctx context.Context, paymentID pgtype.UUID) ([]LedgerEntry, error)
	ListPaymentsForAutoRefund(ctx context.Context, arg ListPaymentsForAutoRefundParams) ([]Payment, error)
	ListStuckPayments(ctx context.Context, arg ListStuckPaymentsParams) ([]Payment, error)
	ListTrustedMerchants(ctx context.Context, userID pgtype.UUID) ([]ListTrustedMerchantsRow, error)
	ListUserAuditEvents(ctx context.Context, arg ListUserAuditEventsParams) ([]AuditEvent, error)
	ListUserDeviceSessions(ctx context.Context, userID pgtype.UUID) ([]DeviceSession, error)
	ListUserLedger(ctx context.Context, arg ListUserLedgerParams) ([]LedgerEntry, error)
	ListUserMandates(ctx context.Context, userID pgtype.UUID) ([]Mandate, error)
	ListUserPayments(ctx context.Context, arg ListUserPaymentsParams) ([]Payment, error)
	ListUserPushTokens(ctx context.Context, userID pgtype.UUID) ([]PushToken, error)
	ListUserPushTokensExceptSession(ctx context.Context, arg ListUserPushTokensExceptSessionParams) ([]PushToken, error)
	MarkOTPVerified(ctx context.Context, id pgtype.UUID) error
	MarkPaymentAutoRefunded(ctx context.Context, arg MarkPaymentAutoRefundedParams) (Payment, error)
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error)
	// Conditional on status=held so undo can't fire after the hold has been
	// released into transfer.
	MarkPaymentRefunded(ctx context.Context, arg MarkPaymentRefundedParams) (Payment, error)
	MarkPaymentSettled(ctx context.Context, id pgtype.UUID) (Payment, error)
	MarkPendingLimitApplied(ctx context.Context, id pgtype.UUID) error
	MarkTokenFailed(ctx context.Context, id pgtype.UUID) (Token, error)
	MarkTokenSettled(ctx context.Context, arg MarkTokenSettledParams) (Token, error)
	// Conditional on status=held so the undo path and the release path don't
	// both try to advance the payment. Whoever wins the UPDATE proceeds.
	ReleaseHeldPayment(ctx context.Context, id pgtype.UUID) (Payment, error)
	RevokeAllOtherDeviceSessions(ctx context.Context, arg RevokeAllOtherDeviceSessionsParams) error
	RevokeDeviceSession(ctx context.Context, arg RevokeDeviceSessionParams) error
	RevokeMandate(ctx context.Context, arg RevokeMandateParams) error
	RevokePushToken(ctx context.Context, fcmToken string) error
	RevokePushTokensForSession(ctx context.Context, deviceSessionID pgtype.UUID) error
	SetDefaultMandate(ctx context.Context, arg SetDefaultMandateParams) (Mandate, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error)
	SumUserSentLast24h(ctx context.Context, senderUserID pgtype.UUID) (int64, error)
	TouchDeviceSession(ctx context.Context, arg TouchDeviceSessionParams) error
	UnsetDefaultMandate(ctx context.Context, userID pgtype.UUID) error
	UpdatePaymentCharge(ctx context.Context, arg UpdatePaymentChargeParams) (Payment, error)
	UpdatePaymentTransfer(ctx context.Context, arg UpdatePaymentTransferParams) (Payment, error)
	UpdateUserKYC(ctx context.Context, arg UpdateUserKYCParams) (User, error)
	UpdateUserLimits(ctx context.Context, arg UpdateUserLimitsParams) (User, error)
	UpdateUserReceiveAccount(ctx context.Context, arg UpdateUserReceiveAccountParams) (User, error)
	UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) (PushToken, error)
	UpsertTrustedMerchant(ctx context.Context, arg UpsertTrustedMerchantParams) (TrustedMerchant, error)
}

var _ Querier = (*Queries)(nil)
