// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimToken(ctx context.Context, arg ClaimTokenParams) (Token, error)
	CreateMandate(ctx context.Context, arg CreateMandateParams) (Mandate, error)
	CreateOTPRequest(ctx context.Context, arg CreateOTPRequestParams) (OtpRequest, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateUser(ctx context.Context, phone string) (User, error)
	ExpirePreviousOTPs(ctx context.Context, arg ExpirePreviousOTPsParams) error
	ExpireStaleTokens(ctx context.Context) error
	GetDefaultMandate(ctx context.Context, userID pgtype.UUID) (Mandate, error)
	GetLatestOTPRequest(ctx context.Context, arg GetLatestOTPRequestParams) (OtpRequest, error)
	GetMandateByID(ctx context.Context, id pgtype.UUID) (Mandate, error)
	GetPaymentByChargeReference(ctx context.Context, chargeReference *string) (Payment, error)
	GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error)
	GetPaymentByTransferReference(ctx context.Context, transferReference *string) (Payment, error)
	GetTokenByCode(ctx context.Context, code string) (Token, error)
	GetTokenByID(ctx context.Context, id pgtype.UUID) (Token, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) (OtpRequest, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error)
	ListPaymentLedger(ctx context.Context, paymentID pgtype.UUID) ([]LedgerEntry, error)
	ListStuckPayments(ctx context.Context, arg ListStuckPaymentsParams) ([]Payment, error)
	ListUserLedger(ctx context.Context, arg ListUserLedgerParams) ([]LedgerEntry, error)
	ListUserMandates(ctx context.Context, userID pgtype.UUID) ([]Mandate, error)
	ListUserPayments(ctx context.Context, arg ListUserPaymentsParams) ([]Payment, error)
	MarkOTPVerified(ctx context.Context, id pgtype.UUID) error
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (Payment, error)
	MarkPaymentSettled(ctx context.Context, id pgtype.UUID) (Payment, error)
	MarkTokenFailed(ctx context.Context, id pgtype.UUID) (Token, error)
	MarkTokenSettled(ctx context.Context, arg MarkTokenSettledParams) (Token, error)
	RevokeMandate(ctx context.Context, arg RevokeMandateParams) error
	SetDefaultMandate(ctx context.Context, arg SetDefaultMandateParams) (Mandate, error)
	SumUserSentLast24h(ctx context.Context, senderUserID pgtype.UUID) (int64, error)
	UnsetDefaultMandate(ctx context.Context, userID pgtype.UUID) error
	UpdatePaymentCharge(ctx context.Context, arg UpdatePaymentChargeParams) (Payment, error)
	UpdatePaymentTransfer(ctx context.Context, arg UpdatePaymentTransferParams) (Payment, error)
	UpdateUserKYC(ctx context.Context, arg UpdateUserKYCParams) (User, error)
	UpdateUserLimits(ctx context.Context, arg UpdateUserLimitsParams) (User, error)
	UpdateUserReceiveAccount(ctx context.Context, arg UpdateUserReceiveAccountParams) (User, error)
}

var _ Querier = (*Queries)(nil)
