// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimToken = `-- name: ClaimToken :one
UPDATE tokens
SET status = 'claimed',
    claimed_by_user_id = $2,
    claimed_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND status = 'created' AND expires_at > NOW()
RETURNING id, code, issued_by_user_id, amount_kobo, note, status, claimed_by_user_id, claimed_at, expires_at, settled_payment_id, created_at, updated_at
`

type ClaimTokenParams struct {
	ID              pgtype.UUID `json:"id"`
	ClaimedByUserID pgtype.UUID `json:"claimed_by_user_id"`
}

func (q *Queries) ClaimToken(ctx context.Context, arg ClaimTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, claimToken, arg.ID, arg.ClaimedByUserID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IssuedByUserID,
		&i.AmountKobo,
		&i.Note,
		&i.Status,
		&i.ClaimedByUserID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.SettledPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (code, issued_by_user_id, amount_kobo, note, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, issued_by_user_id, amount_kobo, note, status, claimed_by_user_id, claimed_at, expires_at, settled_payment_id, created_at, updated_at
`

type CreateTokenParams struct {
	Code           string             `json:"code"`
	IssuedByUserID pgtype.UUID        `json:"issued_by_user_id"`
	AmountKobo     int64              `json:"amount_kobo"`
	Note           *string            `json:"note"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.Code,
		arg.IssuedByUserID,
		arg.AmountKobo,
		arg.Note,
		arg.ExpiresAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IssuedByUserID,
		&i.AmountKobo,
		&i.Note,
		&i.Status,
		&i.ClaimedByUserID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.SettledPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireStaleTokens = `-- name: ExpireStaleTokens :exec
UPDATE tokens
SET status = 'expired',
    updated_at = NOW()
WHERE status = 'created' AND expires_at <= NOW()
`

func (q *Queries) ExpireStaleTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireStaleTokens)
	return err
}

const getTokenByCode = `-- name: GetTokenByCode :one
SELECT id, code, issued_by_user_id, amount_kobo, note, status, claimed_by_user_id, claimed_at, expires_at, settled_payment_id, created_at, updated_at FROM tokens WHERE code = $1
`

func (q *Queries) GetTokenByCode(ctx context.Context, code string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByCode, code)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IssuedByUserID,
		&i.AmountKobo,
		&i.Note,
		&i.Status,
		&i.ClaimedByUserID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.SettledPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, code, issued_by_user_id, amount_kobo, note, status, claimed_by_user_id, claimed_at, expires_at, settled_payment_id, created_at, updated_at FROM tokens WHERE id = $1
`

func (q *Queries) GetTokenByID(ctx context.Context, id pgtype.UUID) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByID, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IssuedByUserID,
		&i.AmountKobo,
		&i.Note,
		&i.Status,
		&i.ClaimedByUserID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.SettledPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTokenFailed = `-- name: MarkTokenFailed :one
UPDATE tokens
SET status = 'failed',
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, issued_by_user_id, amount_kobo, note, status, claimed_by_user_id, claimed_at, expires_at, settled_payment_id, created_at, updated_at
`

func (q *Queries) MarkTokenFailed(ctx context.Context, id pgtype.UUID) (Token, error) {
	row := q.db.QueryRow(ctx, markTokenFailed, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IssuedByUserID,
		&i.AmountKobo,
		&i.Note,
		&i.Status,
		&i.ClaimedByUserID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.SettledPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTokenSettled = `-- name: MarkTokenSettled :one
UPDATE tokens
SET status = 'settled',
    settled_payment_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, issued_by_user_id, amount_kobo, note, status, claimed_by_user_id, claimed_at, expires_at, settled_payment_id, created_at, updated_at
`

type MarkTokenSettledParams struct {
	ID               pgtype.UUID `json:"id"`
	SettledPaymentID pgtype.UUID `json:"settled_payment_id"`
}

func (q *Queries) MarkTokenSettled(ctx context.Context, arg MarkTokenSettledParams) (Token, error) {
	row := q.db.QueryRow(ctx, markTokenSettled, arg.ID, arg.SettledPaymentID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IssuedByUserID,
		&i.AmountKobo,
		&i.Note,
		&i.Status,
		&i.ClaimedByUserID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.SettledPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
