// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trusted_merchants.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTrustedMerchant = `-- name: DeleteTrustedMerchant :exec
DELETE FROM trusted_merchants
WHERE id = $1 AND user_id = $2
`

type DeleteTrustedMerchantParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTrustedMerchant(ctx context.Context, arg DeleteTrustedMerchantParams) error {
	_, err := q.db.Exec(ctx, deleteTrustedMerchant, arg.ID, arg.UserID)
	return err
}

const getTrustedMerchantCap = `-- name: GetTrustedMerchantCap :one
SELECT per_tx_cap_kobo FROM trusted_merchants
WHERE user_id = $1 AND merchant_user_id = $2
`

type GetTrustedMerchantCapParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	MerchantUserID pgtype.UUID `json:"merchant_user_id"`
}

func (q *Queries) GetTrustedMerchantCap(ctx context.Context, arg GetTrustedMerchantCapParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTrustedMerchantCap, arg.UserID, arg.MerchantUserID)
	var per_tx_cap_kobo int64
	err := row.Scan(&per_tx_cap_kobo)
	return per_tx_cap_kobo, err
}

const listTrustedMerchants = `-- name: ListTrustedMerchants :many
SELECT tm.id, tm.user_id, tm.merchant_user_id, tm.per_tx_cap_kobo, tm.label, tm.created_at, tm.updated_at, u.full_name AS merchant_name, u.phone AS merchant_phone
FROM trusted_merchants tm
JOIN users u ON u.id = tm.merchant_user_id
WHERE tm.user_id = $1
ORDER BY tm.created_at DESC
`

type ListTrustedMerchantsRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	MerchantUserID pgtype.UUID        `json:"merchant_user_id"`
	PerTxCapKobo   int64              `json:"per_tx_cap_kobo"`
	Label          *string            `json:"label"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	MerchantName   *string            `json:"merchant_name"`
	MerchantPhone  string             `json:"merchant_phone"`
}

func (q *Queries) ListTrustedMerchants(ctx context.Context, userID pgtype.UUID) ([]ListTrustedMerchantsRow, error) {
	rows, err := q.db.Query(ctx, listTrustedMerchants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrustedMerchantsRow
	for rows.Next() {
		var i ListTrustedMerchantsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantUserID,
			&i.PerTxCapKobo,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MerchantName,
			&i.MerchantPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrustedMerchant = `-- name: UpsertTrustedMerchant :one
INSERT INTO trusted_merchants (user_id, merchant_user_id, per_tx_cap_kobo, label)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, merchant_user_id)
DO UPDATE SET per_tx_cap_kobo = EXCLUDED.per_tx_cap_kobo,
              label = EXCLUDED.label,
              updated_at = NOW()
RETURNING id, user_id, merchant_user_id, per_tx_cap_kobo, label, created_at, updated_at
`

type UpsertTrustedMerchantParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	MerchantUserID pgtype.UUID `json:"merchant_user_id"`
	PerTxCapKobo   int64       `json:"per_tx_cap_kobo"`
	Label          *string     `json:"label"`
}

func (q *Queries) UpsertTrustedMerchant(ctx context.Context, arg UpsertTrustedMerchantParams) (TrustedMerchant, error) {
	row := q.db.QueryRow(ctx, upsertTrustedMerchant,
		arg.UserID,
		arg.MerchantUserID,
		arg.PerTxCapKobo,
		arg.Label,
	)
	var i TrustedMerchant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantUserID,
		&i.PerTxCapKobo,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
