// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone)
VALUES ($1)
RETURNING id, phone, full_name, bvn_hash, date_of_birth, kyc_tier, kyc_status, nuban, bank_code, account_name, per_tx_limit_kobo, per_day_limit_kobo, status, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.BvnHash,
		&i.DateOfBirth,
		&i.KycTier,
		&i.KycStatus,
		&i.Nuban,
		&i.BankCode,
		&i.AccountName,
		&i.PerTxLimitKobo,
		&i.PerDayLimitKobo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, full_name, bvn_hash, date_of_birth, kyc_tier, kyc_status, nuban, bank_code, account_name, per_tx_limit_kobo, per_day_limit_kobo, status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.BvnHash,
		&i.DateOfBirth,
		&i.KycTier,
		&i.KycStatus,
		&i.Nuban,
		&i.BankCode,
		&i.AccountName,
		&i.PerTxLimitKobo,
		&i.PerDayLimitKobo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, full_name, bvn_hash, date_of_birth, kyc_tier, kyc_status, nuban, bank_code, account_name, per_tx_limit_kobo, per_day_limit_kobo, status, created_at, updated_at FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.BvnHash,
		&i.DateOfBirth,
		&i.KycTier,
		&i.KycStatus,
		&i.Nuban,
		&i.BankCode,
		&i.AccountName,
		&i.PerTxLimitKobo,
		&i.PerDayLimitKobo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, phone, full_name, bvn_hash, date_of_birth, kyc_tier, kyc_status, nuban, bank_code, account_name, per_tx_limit_kobo, per_day_limit_kobo, status, created_at, updated_at
`

type SetUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.BvnHash,
		&i.DateOfBirth,
		&i.KycTier,
		&i.KycStatus,
		&i.Nuban,
		&i.BankCode,
		&i.AccountName,
		&i.PerTxLimitKobo,
		&i.PerDayLimitKobo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumUserSentLast24h = `-- name: SumUserSentLast24h :one
SELECT COALESCE(SUM(amount_kobo), 0)::BIGINT AS total_kobo
FROM payments
WHERE sender_user_id = $1
  AND status IN ('initiated', 'debiting', 'transferring', 'settled')
  AND created_at > NOW() - INTERVAL '24 hours'
`

func (q *Queries) SumUserSentLast24h(ctx context.Context, senderUserID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumUserSentLast24h, senderUserID)
	var total_kobo int64
	err := row.Scan(&total_kobo)
	return total_kobo, err
}

const updateUserKYC = `-- name: UpdateUserKYC :one
UPDATE users
SET full_name = $2,
    bvn_hash = $3,
    date_of_birth = $4,
    kyc_tier = $5,
    kyc_status = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, phone, full_name, bvn_hash, date_of_birth, kyc_tier, kyc_status, nuban, bank_code, account_name, per_tx_limit_kobo, per_day_limit_kobo, status, created_at, updated_at
`

type UpdateUserKYCParams struct {
	ID          pgtype.UUID `json:"id"`
	FullName    *string     `json:"full_name"`
	BvnHash     *string     `json:"bvn_hash"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	KycTier     int16       `json:"kyc_tier"`
	KycStatus   string      `json:"kyc_status"`
}

func (q *Queries) UpdateUserKYC(ctx context.Context, arg UpdateUserKYCParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserKYC,
		arg.ID,
		arg.FullName,
		arg.BvnHash,
		arg.DateOfBirth,
		arg.KycTier,
		arg.KycStatus,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.BvnHash,
		&i.DateOfBirth,
		&i.KycTier,
		&i.KycStatus,
		&i.Nuban,
		&i.BankCode,
		&i.AccountName,
		&i.PerTxLimitKobo,
		&i.PerDayLimitKobo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLimits = `-- name: UpdateUserLimits :one
UPDATE users
SET per_tx_limit_kobo = $2,
    per_day_limit_kobo = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, phone, full_name, bvn_hash, date_of_birth, kyc_tier, kyc_status, nuban, bank_code, account_name, per_tx_limit_kobo, per_day_limit_kobo, status, created_at, updated_at
`

type UpdateUserLimitsParams struct {
	ID              pgtype.UUID `json:"id"`
	PerTxLimitKobo  int64       `json:"per_tx_limit_kobo"`
	PerDayLimitKobo int64       `json:"per_day_limit_kobo"`
}

func (q *Queries) UpdateUserLimits(ctx context.Context, arg UpdateUserLimitsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLimits, arg.ID, arg.PerTxLimitKobo, arg.PerDayLimitKobo)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.BvnHash,
		&i.DateOfBirth,
		&i.KycTier,
		&i.KycStatus,
		&i.Nuban,
		&i.BankCode,
		&i.AccountName,
		&i.PerTxLimitKobo,
		&i.PerDayLimitKobo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserReceiveAccount = `-- name: UpdateUserReceiveAccount :one
UPDATE users
SET nuban = $2,
    bank_code = $3,
    account_name = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, phone, full_name, bvn_hash, date_of_birth, kyc_tier, kyc_status, nuban, bank_code, account_name, per_tx_limit_kobo, per_day_limit_kobo, status, created_at, updated_at
`

type UpdateUserReceiveAccountParams struct {
	ID          pgtype.UUID `json:"id"`
	Nuban       *string     `json:"nuban"`
	BankCode    *string     `json:"bank_code"`
	AccountName *string     `json:"account_name"`
}

func (q *Queries) UpdateUserReceiveAccount(ctx context.Context, arg UpdateUserReceiveAccountParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserReceiveAccount,
		arg.ID,
		arg.Nuban,
		arg.BankCode,
		arg.AccountName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.BvnHash,
		&i.DateOfBirth,
		&i.KycTier,
		&i.KycStatus,
		&i.Nuban,
		&i.BankCode,
		&i.AccountName,
		&i.PerTxLimitKobo,
		&i.PerDayLimitKobo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
